version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
      - "3306:3306"
    volumes:
      - "/home/paolo/Documenti/QNOMOS (SSM)/SORGENTI/SSM-BE-master/src:/var/www/html"
    environment:
      DEBUG: "true"
    env_file:
      - .env
    network_mode: "host"
    # extra_hosts:
    #   docker.host: "127.0.0.1"
